[package]
name = "ft_linear_regression"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
csv = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
plotters = "0.3"
plotters-cairo = "0.3"
colored = "2"
open = "5"
